###############################################
# Example using the tessatech/wiremock-server 
# image to deploy a mock server
###############################################

FROM tessatech/wiremock-server:latest as build

COPY ["mock", "/wiremock/"]